
- name: "Fix chipmunk effect with headset"
  hosts: localhost
  become: yes
  tags:
    - audio
  tasks:
    - name: force the sample rate
      lineinfile:
          path: /etc/pulse/daemon.conf
          state: present
          regexp: '; alternate-sample-rate = 48000'
          line:     'alternate-sample-rate = 48000'
    - name: Restart audio daemon
      shell: pulseaudio -k && alsa force-reload

