- name: "Install - Configure terminator and nerdfonts"
  hosts: localhost
  # become: true
  tags:
    - terminator
  tasks:
    - name: install terminator
      become: yes
      package:
        name: terminator
        state: present

    - name: Set the folders
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.config/terminator/"
        - "~/.fonts/"

    - name: Config terminator
      copy:
        src: ../home/.config/terminator/config
        dest: ~/.config/terminator/config
        mode: '0644'

    # Install those fonts: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DejaVuSansMono
    - name: configure the NerdFont required
      get_url:
        url:  "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: '0664'
      loop:
        - { "url":   "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Bold/DejaVuSansMNerdFontMono-Bold.ttf"
            "dest" : "~/.fonts/DejaVu Sans Mono Bold Nerd Font Complete Mono.ttf" }
        - { "url":   "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/DejaVuSansMNerdFontMono-Regular.ttf"
            "dest" : "~/.fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf" }

