- name: "Install - Configure tmux"
  hosts: localhost
  # become: true
  tags:
    - tmux
  tasks:
    - name: install tmux
      package:
        name: tmux
        state: present

    - name: Config tmux
      copy:
        src: ../home/.tmux.3.1.conf
        dest: ~/.tmux.conf
        mode: '0644'

    - name: configure the Powerline
      git:
        repo: https://github.com/erikw/tmux-powerline.git
        dest: ~/github/tmux-powerline

